### ISSUE TITLE
Under RAVEOS rigel miner unable to mine kawpow (ravencoin) with nicehash pool.

### ISSUE THREAD

**Issue by ikorzha** [rigelminer/rigel#125] opened 2024-01-02 03:56 UTC
I have an issue under raveos mining kawpow algo to nicehash. Miner doesn't understand that --a1 kawpow = ravencoin
Can you please add another variable for kawpow in upcoming release.
I have tested if I manually run the string with --a1 ravencoin with nicehash under raveos it works.

Log of the command run by raveos below

root@RIG11:/run/miners/d3bdc281-e0d6-467a-8cc2-f62280227711# /app-data/miners/rigel-1.12.1/rigel --a1 kawpow -o [1]stratum+tcp://kawpow.auto.nicehash.com:9200 -
u [1]3LaM82ASGXEfkbURk7GyYbgSssLZJhEwI7 -p x -w RIG11 --api-bind 127.0.0.1:5501 --no-tui --log-file /var/log/app/miners/rigel-1.12.1-nvidia.log
error: Invalid value 'kawpow' for '--a1 <ALGORITHM>': did you mean `ravencoin` / `neoxa` / `neurai` / `clore` / `aipg` ?

**Comment by rigelminer** [comment] 2024-01-02 05:52
Duplicate of https://github.com/rigelminer/rigel/issues/92

**Closed by rigelminer** 2024-01-02 05:52 UTC
