### ISSUE TITLE
Terminal User interface does'nt work with 1.7.x version on win7

### ISSUE THREAD

**Issue by Mihaxxi** [rigelminer/rigel#86] opened 2023-08-30 08:40 UTC
Hello!

Terminal User interface does'nt work with 1.7.x version on win7. With 1.6.x versions no any problems.
Miner does't start with any tokens. 
Screenshot here:
[https://disk.yandex.ru/d/klZTBzOLzg0SoA](url)

Miner work only if add " --no-tui" command.

Can you fix it?

**Comment by rigelminer** [comment] 2023-09-15 20:03
Hi. This is likely to do with migrating to a fork of the TUI library Rigel depends on in version 1.7.0. The old one no longer has a maintainer unfortunately.
I need to find time to install Win 7 and see what's going on there, perhaps it's an easy fix.

**Comment by rigelminer** [comment] 2023-10-03 20:57
Update: I did some investigation and found out where the issue is coming from. Raised a ticket with the TUI library maintainer, hope it gets fixed soon. Otherwise I'll patch it myself.

**Comment by rigelminer** [comment] 2023-10-04 12:22
@Mihaxxi I decided to go ahead and patch it since the proper fix upstream may take a while. Would you mind trying this build on your Win7 and telling me whether the issue is fixed https://www.dropbox.com/scl/fi/mcdk6q30aq1fefn5utc4w/rigel-1.9.1-win7-win.zip?rlkey=od95540ix9pprpmh6l6gmpy8x&dl=1? If so, I'll include this fix in the next release.

**Comment by Mihaxxi** [comment] 2023-10-04 21:06
> @Mihaxxi I decided to go ahead and patch it since the proper fix upstream may take a while. Would you mind trying this build on your Win7 and telling me whether the issue is fixed https://www.dropbox.com/scl/fi/mcdk6q30aq1fefn5utc4w/rigel-1.9.1-win7-win.zip?rlkey=od95540ix9pprpmh6l6gmpy8x&dl=1? If so, I'll include this fix in the next release.

Hi! Yes, thank's. I trying right now.

**Comment by Mihaxxi** [comment] 2023-10-04 21:06
> @Mihaxxi I decided to go ahead and patch it since the proper fix upstream may take a while. Would you mind trying this build on your Win7 and telling me whether the issue is fixed https://www.dropbox.com/scl/fi/mcdk6q30aq1fefn5utc4w/rigel-1.9.1-win7-win.zip?rlkey=od95540ix9pprpmh6l6gmpy8x&dl=1? If so, I'll include this fix in the next release.

yes, it's work! thank's!!!

**Comment by rigelminer** [comment] 2023-10-04 21:08
Great! Thanks for testing. I'll keep this issue open until I release the fix.

**Comment by mrahmed112** [comment] 2023-10-11 11:27
> @Mihaxxi I decided to go ahead and patch it since the proper fix upstream may take a while. Would you mind trying this build on your Win7 and telling me whether the issue is fixed https://www.dropbox.com/scl/fi/mcdk6q30aq1fefn5utc4w/rigel-1.9.1-win7-win.zip?rlkey=od95540ix9pprpmh6l6gmpy8x&dl=1? If so, I'll include this fix in the next release.

yes, it's work for me too! thank's!!!

**Comment by rigelminer** [comment] 2023-11-09 20:19
Fixed in 1.9.2

**Closed by rigelminer** 2023-11-09 20:19 UTC
