### ISSUE TITLE
FEEDBACK AND FEATURE REQUEST FOR RIGEL MINER [WINDOWS]: THE MINER FAILS TO RESET ITS SETTINGS ON WINDOWS AFTER CLOSURE.

### ISSUE THREAD

**Issue by Aloprinha** [rigelminer/rigel#139] opened 2024-02-11 17:39 UTC
Dear RIGEL Development Team,

I hope this message finds you well. I am writing to provide some feedback and request a feature enhancement for the RIGEL v1.14.2 miner on Windows.

I've been actively using RIGEL for mining KLS+ZIL, and overall, I've been quite pleased with its performance. However, I recently encountered a minor inconvenience that I believe could be addressed for an improved user experience.

Specifically, I noticed that when I close the miner using the CTRL+C command, only the fan controls are reset, while the core clock and memory clock overclock settings remain locked. It would greatly enhance the usability of the miner if it could automatically reset these overclock settings to their default values upon closure, similar to the behavior of other mining software available.

Therefore, I kindly request that you consider implementing a command or enhancement in the next version of RIGEL that ensures the reset of GPU overclock settings to default values upon miner shutdown. This would streamline the mining process and mitigate any potential issues arising from inconsistent overclock settings.

Thank you for your attention to this matter. I appreciate your dedication to continually improving the RIGEL miner, and I look forward to seeing how it evolves in the future.

Best regards,
Aloprinha
[rigel_karlsenhash_zil_20240211_141212.log](https://github.com/rigelminer/rigel/files/14233357/rigel_karlsenhash_zil_20240211_141212.log)

**Comment by rigelminer** [comment] 2024-02-11 19:24
Hi. As I explained in https://github.com/rigelminer/rigel/issues/111 the miner resets the overclock settings to the ones that were applied to the GPU before launching rigel. If you started the miner when the OC was stock (=no OC), it will reset it to stock after exit.
From your log, the GPU must've been at "core offset +150", "memory offset +0", "locked core 1680", "locked memory 810" before you started the miner.
If you reboot the machine, make sure the GPU is at stock, start the miner, terminate it with Ctrl+C, you'll notice it resets the OC.
Now that I explained how the OC logic works, are you saying there is a bug? Or are you asking for a feature where rigel would reset the OC to stock even if the original OC was not stock?

**Comment by Aloprinha** [comment] 2024-02-11 20:51
Understood. After conducting several tests, I've confirmed that it works correctly when closing the miner with CTRL+C. However, when closing the miner without using CTRL+C, the overclock remains stuck, requiring a computer restart.

#Before restarting Windows.

[2024-02-11 14:20:12.467] 
[2024-02-11 14:20:29.886] CTRL+C received, exiting
[2024-02-11 14:20:30.069] GPU#0: fan control set to system managed
[2024-02-11 14:20:30.085] all devices stopped
[2024-02-11 14:20:30.085] all miner tasks finished
[2024-02-11 14:20:30.085] miner terminated

#After restarting Windows.

[2024-02-11 17:34:10.844] 
[2024-02-11 17:34:12.404] CTRL+C received, exiting
[2024-02-11 17:34:12.746] GPU#0: core offset set to +0
[2024-02-11 17:34:12.755] GPU#0: power limit set to 172
[2024-02-11 17:34:12.767] GPU#0: locked core set to `unlocked`
[2024-02-11 17:34:12.775] GPU#0: locked memory set to `unlocked`
[2024-02-11 17:34:12.775] GPU#0: fan control set to system managed
[2024-02-11 17:34:12.798] all devices stopped
[2024-02-11 17:34:12.798] all miner tasks finished
[2024-02-11 17:34:12.798] miner terminated

It would be beneficial if the miner automatically reset the overclock to stock when closed, without entering the “CTRL+C” command, like other miners do.

**Comment by rigelminer** [comment] 2024-02-11 20:58
Okay, then it's a duplicate of https://github.com/rigelminer/rigel/issues/132 :)

**Closed by rigelminer** 2024-02-11 20:58 UTC
