### ISSUE TITLE
Any chance to fix nicehash alephium?

### ISSUE THREAD

**Issue by angelbbs** [rigelminer/rigel#168] opened 2024-04-01 05:44 UTC
`
[2024-03-26 22:03:04] +========================== alephium ==========================+

[2024-03-26 22:03:04] |#|Name          | Hashrate |   Pool   |Acc|Rej |Inv|   Eff    |

[2024-03-26 22:03:04] |0|RTX 2070 SUPER|1.359 GH/s|94.10 MH/s| 33| 725|  0|9.692 MH/W|
[2024-03-26 22:03:04] |1|RTX 3060      |1.005 GH/s|86.86 MH/s| 32| 468|  0|7.401 MH/W|
[2024-03-26 22:03:04] |2|GTX 1070      |608.1 MH/s|33.78 MH/s| 12| 325|  0|5.993 MH/W|
[2024-03-26 22:03:04] |3|GTX 1070      |696.6 MH/s|77.21 MH/s| 20| 356|  0|4.769 MH/W|
[2024-03-26 22:03:04] +-+--------------+----------+----------+---+----+---+----------+
[2024-03-26 22:03:04] |          Total: 3.669 GH/s|292.0 MH/s| 97|1874|  0|7.008 MH/W|
[2024-03-26 22:03:04] +==============================================================+
[2024-03-26 22:03:04]
[2024-03-26 22:03:05] [alephium.auto.nicehash.com:9200] GPU#1 solution rejected - Duplicate share. (89ms)
[2024-03-26 22:03:05] [alephium.auto.nicehash.com:9200] GPU#3 solution rejected - Duplicate share. (98ms)
`

**Comment by rigelminer** [comment] 2024-04-02 11:54
Duplicate of https://github.com/rigelminer/rigel/issues/167

**Closed by rigelminer** 2024-04-02 11:54 UTC
