### ISSUE TITLE
Error 'error: invalid peer certificate contents: invalid peer certificate: UnsupportedCertVersion' mining SHA512256d@zpool (SSL)

### ISSUE THREAD

**Issue by UselessGuru** [rigelminer/rigel#83] opened 2023-08-14 05:44 UTC
Command line used:
`Bin\Rigel-v1.6.4\Rigel.exe --algorithm sha512256d --url [1]stratum+ssl://sha512256d.eu.mine.zpool.ca:53342 --username [1]####################################### --password [1]######################,c=BTC --worker [1]##################### --no-strict-ssl --api-bind 127.0.0.1:4005 --no-watchdog --devices 1`
Non SSL (Port 3342 is working fine.

<img width="1012" alt="image" src="https://github.com/rigelminer/rigel/assets/30080938/c45f821c-5935-4517-9a01-f706106bd901">

**Comment by rigelminer** [comment] 2023-08-16 08:24
I did some investigation and the error appears to be caused by zpool using an old version of X.509 certificates (1 instead of widely used and supported 3).

Zpool
![image](https://github.com/rigelminer/rigel/assets/119491468/e9808503-9e68-48b5-8c82-f608b0520cb3)

Herominers (for comparison)
![image](https://github.com/rigelminer/rigel/assets/119491468/1aab4c42-e231-4fdb-b1d1-257dd2b7e2d7)

The third party library Rigel uses to work with TLS certificates doesn't support version 1 and unfortunately there's nothing I can do about it at the moment.
If you are in touch with the Zpool support team, feel free to forward them the info I provided. Upgrading the certificate to version 3 should fix this issue.

I'm going to close this ticket as I can't fix it from my side.

**Closed by rigelminer** 2023-08-16 08:24 UTC

**Comment by UselessGuru** [comment] 2023-09-19 22:35
Any news? Don't you want to re-open this? It is still unresolved.

**Comment by rigelminer** [comment] 2023-09-20 08:07
Both you and I let them know about the issue https://discord.com/channels/376790817811202050/382162123192795136/1152709466798686428 but I don't know if and when they are going to work on it.
I don't want to re-open the ticket because I can't fix it from my side.

**Comment by crackfoo** [comment] 2023-10-03 04:15
Can someone test this now? I've re-issued the certs and should be v3 now

**Comment by UselessGuru** [comment] 2023-10-03 20:33
I can confirm that this is working now with Rigel (tested with 1.9.1) or Gminer 3.41.


```
Rigel-v1.9.1\Rigel.exe --algorithm ravencoin --url [1]stratum+ssl://kawpow.eu.mine.zergpool.com:13638 --username [1]*********************--password [1]c=BTC,mc=NEOX,ID=*************,pl=0 --worker [1]*************--no-strict-ssl --api-bind 127.0.0.1:4006 --no-watchdog --devices 0
[2023-10-03 22:16:30] Rigel v1.9.1 - [Windows]
[2023-10-03 22:16:30]
[2023-10-03 22:16:30] Driver: v537.42
[2023-10-03 22:16:30]
[2023-10-03 22:16:30] + GPU #0: GTX 1660 SUPER 6G
[2023-10-03 22:16:30] - GPU #1: GT 1030 2G
[2023-10-03 22:16:30] - GPU #2: GTX 750 Ti 2G
[2023-10-03 22:16:30]
[2023-10-03 22:16:30] API server is running at http://127.0.0.1:4006
[2023-10-03 22:16:30] Pools for ravencoin (dev fee 1.0%):
[2023-10-03 22:16:30] URL:    kawpow.eu.mine.zergpool.com:13638
[2023-10-03 22:16:30] User:   1GPSq8txFnyrYdXL8t6S94mYdF8cGqVQJF
[2023-10-03 22:16:30] Pass:   c=BTC,mc=NEOX,ID=Blackbox,pl=0
[2023-10-03 22:16:30] Worker: Blackbox
[2023-10-03 22:16:30]
[2023-10-03 22:16:31] [kawpow.eu.mine.zergpool.com:13638] connecting...
[2023-10-03 22:16:31] [kawpow.eu.mine.zergpool.com:13638] connected
[2023-10-03 22:16:31] [kawpow.eu.mine.zergpool.com:13638] extranonce: 85d7f8
[2023-10-03 22:16:31] [kawpow.eu.mine.zergpool.com:13638] difficulty: 429.50M (0.10)
[2023-10-03 22:16:32] Light cache built
[2023-10-03 22:16:32] GPU#0: building DAG for epoch 95, 1.87 GB
[2023-10-03 22:16:36] CTRL+C received, exiting
[2023-10-03 22:16:37] all devices stopped
[2023-10-03 22:16:37] all miner tasks finished
[2023-10-03 22:16:37] miner terminated
```

@crackfoo Please note that SSL for KawPow is not working anymore with some other miners (i think they only support tls 1.2).

e.g. KawPowMiner:
`Bin\KawpowMiner-v1.2.4cl\kawpowminer.exe --pool stratum+ssl://************************:*****************%2cc%3dBTC%2czap%3dNEOX@kawpow.eu.mine.zpool.ca:51325 --farm-recheck 10000 --farm-retries 40 --work-timeout 100000 --response-timeout 720 --api-bind 127.0.0.1:4001 --cl-devices 1`


kawpowminer 1.2.4+commit.d0e002e6
Build: windows/release/msvc

```
 i 22:16:41 main      Configured pool kawpow.eu.mine.zpool.ca:51325
 i 22:16:41 main      Api server listening on port 4001.
 i 22:16:41 <unknown> Selected pool kawpow.eu.mine.zpool.ca:51325
 X 22:16:41 <unknown> SSL/TLS Handshake failed: tlsv1 alert protocol version
 i 22:16:41 <unknown> Disconnected from kawpow.eu.mine.zpool.ca:51325
 i 22:16:41 <unknown> No connection. Suspend mining ...
 i 22:16:41 <unknown> No more connections to try. Exiting...
 i 22:16:41 main      Got interrupt ...
 i 22:16:41 main      Terminated!
```
However KawpowMiner IS working with ZergPool (which was always working with Rigel, even before ZPools v3 cert change):

`Bin\KawpowMiner-v1.2.4cl\kawpowminer.exe --pool stratum+ssl://*************************:c%3dBTC%2cmc%3dNEOX%2cID%****************%2cpl%3d0@kawpow.eu.mine.zergpool.com:13638 --farm-recheck 10000 --farm-retries 40 --work-timeout 100000 --response-timeout 720 --api-bind 127.0.0.1:4001 --cl-devices 1`

```
kawpowminer 1.2.4+commit.d0e002e6
Build: windows/release/msvc

 i 22:26:29 main      Configured pool kawpow.eu.mine.zergpool.com:13638
 i 22:26:29 main      Api server listening on port 4001.
 i 22:26:29 <unknown> Selected pool kawpow.eu.mine.zergpool.com:13638
 i 22:26:30 <unknown> Stratum mode : Stratum
 i 22:26:30 <unknown> Established connection to kawpow.eu.mine.zergpool.com [141.95.55.97:13638]
 i 22:26:30 <unknown> Spinning up miners...
 i 22:26:30 <unknown> Extranonce set to 800079
 i 22:26:30 <unknown> Authorized worker ******************************
 i 22:26:30 <unknown> New target set to: 00000009fff60000000000000000000000000000000000000000000000000000
 i 22:26:30 <unknown> Epoch : 96 Difficulty : 429.50 Mh
 i 22:26:30 <unknown> Job: c63ef2f2... block 720014 kawpow.eu.mine.zergpool.com [141.95.55.97:13638]
cl 22:26:30 cl-0      Creating buffers
cl 22:26:30 cl-0      Using PciId : 09:00.0 gfx1010:xnack- OpenCL 2.0 AMD-APP (3516.0) Memory : 7.98 GB
 i 22:26:30 cl-0      Adjusting CL work multiplier for 20 CUs. Adjusted work multiplier: 18�205
cl 22:26:31 cl-0      Pre-compiled period 240�004 OpenCL ProgPow kernel
cl 22:26:31 cl-0      Loaded period 240�004 progpow kernel
cl 22:26:31 cl-0      Generating DAG + Light : 1.78 GB
cl 22:26:31 cl-0      Creating light cache buffer, size: 28.00 MB
cl 22:26:31 cl-0      Creating DAG buffer, size: 1.75 GB, free: 6.21 GB
cl 22:26:31 cl-0      Loading kernels
cl 22:26:32 cl-0      Pre-compiled period 240�005 OpenCL ProgPow kernel
cl 22:26:32 cl-0      Writing light cache buffer
 m 22:26:34 <unknown> 0:00 A0 0.00 h - cl0 0.00
 i 22:26:36 <unknown> Job: 7667667a... block 720014 kawpow.eu.mine.zergpool.com [141.95.55.97:13638]
 i 22:26:38 main      Got interrupt ...
 i 22:26:39 <unknown> Disconnected from kawpow.eu.mine.zergpool.com [141.95.55.97:13638]
 i 22:26:39 <unknown> Shutting down miners...
cl 22:26:39 cl-0      1.75 GB of DAG data generated in 7�726 ms.
...
```
Su I assume that ZPools v3 cert implementation is not backwards compatible with older SSL/TSL mechanisms. Maybe ZergPool (PinPin) can assist more.

**Comment by UselessGuru** [comment] 2023-10-05 20:04
ZPool has updated their certificates:

> okay. cert now v3
minimum TLS version 1.2
dropped from 1.3, but that is supported as well (xmrig negotiates this just fine)
