### ISSUE TITLE
Bug with displayed hash 

### ISSUE THREAD

**Issue by 13y87t** [rigelminer/rigel#59] opened 2023-04-25 09:40 UTC
Hello, on IRON with 3080/3090 there is a bug with card by card displayed hashrate in hiveos, it stuck at 1000MHs instead of showing GHs like others

Stats bar is bugged too

![Screenshot_20230425-114007_Chrome](https://user-images.githubusercontent.com/118174931/234237975-73c1c54c-b5cc-4531-b216-ad1189c881d7.jpg)
![Screenshot_20230425-113746_Hive OS](https://user-images.githubusercontent.com/118174931/234237978-aae49ad4-bc7b-4158-ba75-dc6793aa72ae.jpg)

**Comment by rigelminer** [comment] 2023-04-25 10:07
Duplicate of https://github.com/rigelminer/rigel/issues/57

**Closed by rigelminer** 2023-04-25 10:07 UTC

**Comment by 13y87t** [comment] 2023-04-25 10:28
Oups
