### ISSUE TITLE
Low NEXA hashrate when mining NEXA+ZIL

### ISSUE THREAD

**Issue by DervilRus** [rigelminer/rigel#37] opened 2023-03-08 15:37 UTC
If you mine only NEXA, the hashrate is 10% more than if you mine NEXA + ZIL !!!

This is clearly a mistake! Correct please!!!!

**Comment by rigelminer** [comment] 2023-03-08 15:40
Duplicate of https://github.com/rigelminer/rigel/issues/24

**Closed by rigelminer** 2023-03-08 15:40 UTC
