### ISSUE TITLE
Dev-Mining (DAG algorithms) on low mem card crashes miner

### ISSUE THREAD

**Issue by UselessGuru** [rigelminer/rigel#96] opened 2023-10-04 16:32 UTC
`Rigel-v1.9.1\Rigel.exe --algorithm ravencoin --url [1]stratum+ssl://kawpow.eu.mine.zergpool.com:13638 --username [1]****************************--password [1]c=BTC,mc=CLORE,ID=****************,pl=0 --worker [1]Blackbox --no-strict-ssl --api-bind 127.0.0.1:4005 --no-watchdog --devices 1`

```
[2023-10-04 18:21:25] Rigel v1.9.1 - [Windows]
[2023-10-04 18:21:25]
[2023-10-04 18:21:25] Driver: v537.42
[2023-10-04 18:21:25]
[2023-10-04 18:21:25] - GPU #0: GTX 1660 SUPER 6G
[2023-10-04 18:21:25] + GPU #1: GT 1030 2G
[2023-10-04 18:21:25] - GPU #2: GTX 750 Ti 2G
[2023-10-04 18:21:25]
[2023-10-04 18:21:25] API server is running at http://127.0.0.1:4005
[2023-10-04 18:21:25] Pools for ravencoin (dev fee 1.0%):
[2023-10-04 18:21:25] URL:    kawpow.eu.mine.zergpool.com:13638
[2023-10-04 18:21:25] User:   *************************************
[2023-10-04 18:21:25] Pass:   c=BTC,mc=CLORE,ID=********************,pl=0
[2023-10-04 18:21:25] Worker: Blackbox
[2023-10-04 18:21:25]
[2023-10-04 18:21:25] [kawpow.eu.mine.zergpool.com:13638] connecting...
[2023-10-04 18:21:25] [kawpow.eu.mine.zergpool.com:13638] connected
[2023-10-04 18:21:25] [kawpow.eu.mine.zergpool.com:13638] extranonce: 8628de
[2023-10-04 18:21:25] [kawpow.eu.mine.zergpool.com:13638] difficulty: 429.50M (0.10)
[2023-10-04 18:21:26] Light cache built
[2023-10-04 18:21:26] GPU#1: building DAG for epoch 57, 1.55 GB
[2023-10-04 18:21:45]
[2023-10-04 18:21:45] +================== Rigel v1.9.1 - [Windows] ==================+
[2023-10-04 18:21:45] |#|Name   |Power|T(core)|T(mem)|Fan|    Core    |    Memory    |
[2023-10-04 18:21:45] |1|GT 1030|  n/a|   52°C|   n/a|45%|1936MHz (+0)|3453MHz (  +0)|
[2023-10-04 18:21:45] +-+-------+-----+-------+------+---+------------+--------------+
[2023-10-04 18:21:45] |     Total: n/a|             Uptime: 0d 00:00:20              |
[2023-10-04 18:21:45] +==============================================================+
[2023-10-04 18:21:45]
[2023-10-04 18:21:45] +============== ravencoin ==============+
[2023-10-04 18:21:45] |#|Name   |Hashrate|Pool|Acc|Rej|Inv|Eff|
[2023-10-04 18:21:45] |1|GT 1030|       -|   -|  0|  0|  0|n/a|
[2023-10-04 18:21:45] +-+-------+--------+----+---+---+---+---+
[2023-10-04 18:21:45] |          Total: -|   -|  0|  0|  0|n/a|
[2023-10-04 18:21:45] +=======================================+
[2023-10-04 18:21:45]
[2023-10-04 18:21:58] GPU#1: DAG built in 32.7s
[2023-10-04 18:22:05]
[2023-10-04 18:22:05] +================== Rigel v1.9.1 - [Windows] ==================+
[2023-10-04 18:22:05] |#|Name   |Power|T(core)|T(mem)|Fan|    Core    |    Memory    |
[2023-10-04 18:22:05] |1|GT 1030|  n/a|   57°C|   n/a|48%|1670MHz (+0)|3453MHz (  +0)|
[2023-10-04 18:22:05] +-+-------+-----+-------+------+---+------------+--------------+
[2023-10-04 18:22:05] |     Total: n/a|             Uptime: 0d 00:00:40              |
[2023-10-04 18:22:05] +==============================================================+
[2023-10-04 18:22:05]
[2023-10-04 18:22:05] +=============== ravencoin ===============+
[2023-10-04 18:22:05] |#|Name   | Hashrate |Pool|Acc|Rej|Inv|Eff|
[2023-10-04 18:22:05] |1|GT 1030|2.809 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:22:05] +-+-------+----------+----+---+---+---+---+
[2023-10-04 18:22:05] |   Total: 2.809 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:22:05] +=========================================+
[2023-10-04 18:22:05]
[2023-10-04 18:22:25]
[2023-10-04 18:22:25] +================== Rigel v1.9.1 - [Windows] ==================+
[2023-10-04 18:22:25] |#|Name   |Power|T(core)|T(mem)|Fan|    Core    |    Memory    |
[2023-10-04 18:22:25] |1|GT 1030|  n/a|   61°C|   n/a|50%|1632MHz (+0)|3453MHz (  +0)|
[2023-10-04 18:22:25] +-+-------+-----+-------+------+---+------------+--------------+
[2023-10-04 18:22:25] |     Total: n/a|             Uptime: 0d 00:01:00              |
[2023-10-04 18:22:25] +==============================================================+
[2023-10-04 18:22:25]
[2023-10-04 18:22:25] +=============== ravencoin ===============+
[2023-10-04 18:22:25] |#|Name   | Hashrate |Pool|Acc|Rej|Inv|Eff|
[2023-10-04 18:22:25] |1|GT 1030|2.866 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:22:25] +-+-------+----------+----+---+---+---+---+
[2023-10-04 18:22:25] |   Total: 2.866 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:22:25] +=========================================+
[2023-10-04 18:22:25]
[2023-10-04 18:22:45]
[2023-10-04 18:22:45] +================== Rigel v1.9.1 - [Windows] ==================+
[2023-10-04 18:22:45] |#|Name   |Power|T(core)|T(mem)|Fan|    Core    |    Memory    |
[2023-10-04 18:22:45] |1|GT 1030|  n/a|   64°C|   n/a|51%|1683MHz (+0)|3453MHz (  +0)|
[2023-10-04 18:22:45] +-+-------+-----+-------+------+---+------------+--------------+
[2023-10-04 18:22:45] |     Total: n/a|             Uptime: 0d 00:01:20              |
[2023-10-04 18:22:45] +==============================================================+
[2023-10-04 18:22:45]
[2023-10-04 18:22:45] +=============== ravencoin ===============+
[2023-10-04 18:22:45] |#|Name   | Hashrate |Pool|Acc|Rej|Inv|Eff|
[2023-10-04 18:22:45] |1|GT 1030|2.865 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:22:45] +-+-------+----------+----+---+---+---+---+
[2023-10-04 18:22:45] |   Total: 2.865 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:22:45] +=========================================+
[2023-10-04 18:22:45]
[2023-10-04 18:23:05]
[2023-10-04 18:23:05] +================== Rigel v1.9.1 - [Windows] ==================+
[2023-10-04 18:23:05] |#|Name   |Power|T(core)|T(mem)|Fan|    Core    |    Memory    |
[2023-10-04 18:23:05] |1|GT 1030|  n/a|   66°C|   n/a|54%|1632MHz (+0)|3453MHz (  +0)|
[2023-10-04 18:23:05] +-+-------+-----+-------+------+---+------------+--------------+
[2023-10-04 18:23:05] |     Total: n/a|             Uptime: 0d 00:01:40              |
[2023-10-04 18:23:05] +==============================================================+
[2023-10-04 18:23:05]
[2023-10-04 18:23:05] +=============== ravencoin ===============+
[2023-10-04 18:23:05] |#|Name   | Hashrate |Pool|Acc|Rej|Inv|Eff|
[2023-10-04 18:23:05] |1|GT 1030|2.640 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:23:05] +-+-------+----------+----+---+---+---+---+
[2023-10-04 18:23:05] |   Total: 2.640 MH/s|   -|  0|  0|  0|n/a|
[2023-10-04 18:23:05] +=========================================+
[2023-10-04 18:23:05]
[2023-10-04 18:23:06] Light cache built
[2023-10-04 18:23:06] GPU#1: building DAG for epoch 400, 4.43 GB
[2023-10-04 18:23:07] GPU#1 error: CUDA error: insufficient memory
[2023-10-04 18:23:07] all devices stopped
[2023-10-04 18:23:07] all miner tasks finished
[2023-10-04 18:23:07] miner terminated
```

Mining works fine with no switching until dev mining kicks in and attempts to allocate memory for a larger DAG.
I see 3 possible solutions:
a) Use a low mem coin/pool combo for DEV mining that fits in memory
b) suspend mining instead of attemting to swich DAG, and resume when dev mining time is over
c) no DEV mining if available memory does not allow dev mining DAG switch

**Comment by rigelminer** [comment] 2023-10-04 16:53
I see you're mining CLORE? If so, instead of `--algorithm ravencoin` set `--algorithm clore` and the miner won't be rebuilding the DAG.

**Comment by UselessGuru** [comment] 2023-10-04 17:48
> and the miner won't be rebuilding the DAG
Thank you for the suggestion.
I see, but that is a bit cumbersome, because this requires adding an extra translation table in the miner PS files.
NemosMiners logic (pretty much same as Rainbow miners logic) pools only return the algo & currency.

RainbowMiner includes this in the miner file to get around the issue:

```
            if ($MainAlgorithm_0 -eq "ravencoin") {
                if ($Pools.$MainAlgorithm_Norm_0.CoinSymbol -eq "CLORE")    {$MainAlgorithm_0 = "clore"}
                elseif ($Pools.$MainAlgorithm_Norm_0.CoinSymbol -eq "NEOX") {$MainAlgorithm_0 = "neoxa"}
                elseif ($Pools.$MainAlgorithm_Norm_0.CoinSymbol -eq "XNA")  {$MainAlgorithm_0 = "neurai"}
                elseif ($Pools.$MainAlgorithm_Norm_0.CoinSymbol -ne "RVN")  {$MainAlgorithm_0 = "neurai"}
            }
```
I would prefer not to onclude such a table. This is why I am setting --algorithm to kawpow and also the mining coin mc=****.

**Comment by UselessGuru** [comment] 2023-10-04 18:11
And how does the DAG switch work for EGAM / ESN / EXP / ETHW?

**Comment by rigelminer** [comment] 2023-10-04 18:39
See the conversation here https://github.com/rigelminer/rigel/issues/92 and here https://github.com/rigelminer/rigel/issues/95, they are all about the same thing. I'm going to close this one to avoid duplication.

**Comment by rigelminer** [comment] 2023-10-04 18:40
Duplicate of https://github.com/rigelminer/rigel/issues/92

**Closed by rigelminer** 2023-10-04 18:40 UTC
