### ISSUE TITLE
some setting using red panda youtube video mining nexa and rigel miner. it over power my whole mining rig and blow my PSU up! fired it man! nevey after 2 years mining that a bad software in this miner would distroy my hardware! so pissed and man ! this BS is BETA! poor code. are the setting in code allows blow my PSU man it was my mining cave Quite 1,600 watt! i wish u would replace! 

### ISSUE THREAD

**Issue by coolrip007** [rigelminer/rigel#46] opened 2023-04-07 03:39 UTC

**Comment by rigelminer** [comment] 2023-04-07 09:30
I'm sorry that happened to you.
Overclocking GPUs is never fully safe, always make sure the total sum of maximum power your GPUs are rated at is less than 80% of what your power supply is rated at to prevent overloading.

**Comment by Strunczez** [comment] 2023-04-12 20:14
Same issue I stated here:
https://github.com/rigelminer/rigel/issues/38
Glad my PSU did not burn down. Glad I bought BeQuiet!
Easiest solution would be to implement a little delay between each GPU start, but I am afraid that Rigel team do not care about this because they did not even respond for my statement.
Sorry for your PSU, hope it did not burn any of your GPU when dying.

**Comment by coolrip007** [comment] 2023-04-12 21:06
thanks sir for reply!! only the psu! got a new evga 1,600 very nice! and also learned a very important lesion on rechecking oc for any errors !lolbeing the miners dont have safe guards in place! hope hacker dont get this flaw but by now after i had posted my findings to all majors mining youtube channels comments pages lol! well theyt know know! Here's my proof srb miner . I discovered a very dangerous  flaw! miners How hacker can burn your mining farms down. SRB Miner refuse to build safe guards into the code!

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How hacker can burn your mining farms down. SRB Miner refuse to build sa...


 |

 |

 |

srb miner is the one! hope u like my 1st vid

    On Wednesday, April 12, 2023 at 03:14:42 PM CDT, Strunczez ***@***.***> wrote:  
 
 


Same issue I stated here:
#38
Glad my PSU did not burn down. Glad I bought BeQuiet!
Easiest solution would be to implement a little delay between each GPU start, but I am afraid that Rigel team do not care about this because they did not even respond for my statement.
Sorry for your PSU, hope it did not burn any of your GPU when dying.

**Comment by peivanov** [comment] 2023-04-21 07:30
Just a suggestion, make sure to always set up watchdog in Hive, there is a setting to set min and max power usage.

**Comment by impulse709** [comment] 2023-04-27 00:26
how is it devs fault that you couldn't be bothered to check your overclocks? Also your cards will only draw what they are rated for if that's more then what your PSU is rated for which it clearly was you should have been running a more powerful PSU or two less powerful ones. this was entirely your fault bud. the software is fantastic. be more careful.

**Comment by Strunczez** [comment] 2023-04-27 02:25
1) Author cheaped on PSU, that's why it burned it out.
2) Software is badly written. It should not pull more Watts that it is set in OC settings, if it pulls more that something is wrong. It also Pulls more when you set limit in miner config. That is bad as F**k.
3) Good software is not only a higher hash rates but also a well written code.

**Comment by rigelminer** [comment] 2023-05-14 08:28
Closing as a duplicate of https://github.com/rigelminer/rigel/issues/38

**Closed by rigelminer** 2023-05-14 08:28 UTC
