### ISSUE TITLE
RTX 2060 Super 8G недостаточно памяти

### ISSUE THREAD

**Issue by asd1968** [rigelminer/rigel#76] opened 2023-06-30 20:03 UTC
RTX 2060 Super 8G недостаточно памяти

**Comment by rigelminer** [comment] 2023-06-30 21:11
Which algorithm are you mining?

**Comment by asd1968** [comment] 2023-06-30 21:16
NexaPow

**Comment by rigelminer** [comment] 2023-06-30 21:17
Thanks. I'll close this particular issue as a duplicate of https://github.com/rigelminer/rigel/issues/72

**Comment by asd1968** [comment] 2023-06-30 21:17
![Снимок экрана (34)](https://github.com/rigelminer/rigel/assets/138253595/b1e8321a-adf7-4e11-a26f-1e4663826704)

**Closed by rigelminer** 2023-06-30 21:17 UTC
